### PR TITLE
Automated Testing

### PR DESCRIPTION
**Pull request by austingulati**
I added some simple unit tests and made a few changes to validations.

For example, we should require either a height or a weight for a measurement since people may not weigh/measure their baby at the same time.

### CODE REVIEW

**Comment by dmastylo** [comment]
Changed validations so that you can do height or weight. Maybe we should require the first one to have both? So that we have some baseline. Thoughts?

**Comment by raymondjacobson** [comment]
Agreed. It should be a requirement.

**Comment by austingulati** [comment]
I dunno, what if someone doesn't want to track their baby's height or weight, we shouldn't force anyone to use the application in a specific way

**Comment by dmastylo** [comment]
No I'm saying if they do wanna track that stuff the initial one should have both measurements.

**Comment by raymondjacobson** [comment]
What's the status of this? Ready to pull?

**Comment by dmastylo** [comment]
I don't think it's fully specced yet

**Comment by raymondjacobson** [comment]
we should merge this and events though so we can keep all that stuff together yeah?

**Comment by dmastylo** [comment]
Nah just do the event testing merge with master this is for testing for
already merged features

**Comment by austingulati** [comment]
Why are we not merging this again?

**Comment by dmastylo** [comment]
not done

Regards,
Damian Mastylo
Co-Founder CodeQuarry, Developer PayWithMe
(913) 370-0735

**Comment by raymondjacobson** [comment]
We have some events tests in here already though. HNNNG

**Pull request merged**
